CREATE TABLE conta(
usuario_id SERIAL PRIMARY KEY,
nomeusuario VARCHAR(50) UNIQUE NOT NULL,
password VARCHAR(50) NOT NULL,
email VARCHAR(250) UNIQUE NOT NULL,
criado_em TIMESTAMP NOT NULL,
ultimo_login TIMESTAMP
)


 
